# Generated by Django 4.2.25 on 2026-05-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('activity_type_id', models.AutoField(db_column='activitytypeid', primary_key=True, serialize=False)),
                ('activity_name', models.CharField(db_column='activityname', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'verbose_name': 'Тип активности',
                'verbose_name_plural': 'Типы активностей',
                'db_table': 'activitytypes',
            },
        ),
        migrations.CreateModel(
            name='FrequencyType',
            fields=[
                ('frequency_id', models.AutoField(db_column='frequencyid', primary_key=True, serialize=False)),
                ('frequency_name', models.CharField(db_column='frequencyname', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип частоты',
                'verbose_name_plural': 'Типы частоты',
                'db_table': 'frequencytypes',
            },
        ),
        migrations.CreateModel(
            name='AnimalCareSchedule',
            fields=[
                ('care_schedule_id', models.AutoField(db_column='scheduleid', primary_key=True, serialize=False)),
                ('schedule_time', models.TimeField(blank=True, db_column='scheduletime', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('is_active', models.BooleanField(db_column='isactive', default=True)),
                ('activity_type', models.ForeignKey(db_column='activitytypeid', on_delete=django.db.models.deletion.DO_NOTHING, to='care.activitytype')),
                ('animal', models.ForeignKey(db_column='animalid', on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('frequency', models.ForeignKey(db_column='frequencyid', on_delete=django.db.models.deletion.DO_NOTHING, to='care.frequencytype')),
            ],
            options={
                'verbose_name': 'Расписание ухода',
                'verbose_name_plural': 'Расписание ухода',
                'db_table': 'animalcareschedule',
            },
        ),
    ]
