# Generated by Django 4.2.25 on 2026-05-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('status_id', models.AutoField(db_column='statusid', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='statusname', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'db_table': 'applicationstatuses',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(db_column='applicationid', primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True, db_column='applicationdate')),
                ('reason', models.TextField(blank=True, db_column='reason', null=True)),
                ('experience', models.TextField(blank=True, db_column='experience', null=True)),
                ('housing_conditions', models.TextField(blank=True, db_column='housingconditions', null=True)),
                ('comment', models.TextField(blank=True, db_column='comment', null=True)),
                ('animal', models.ForeignKey(db_column='animalid', on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('status', models.ForeignKey(db_column='statusid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='applications.applicationstatus')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
            },
        ),
    ]
