-- PostgreSQL bootstrap schema for AnimalShelterDB
-- Converted from MSSQL script to PostgreSQL (initial migration step)
-- Target DB: animalshelterdb

-- =========================================================
-- Core dictionaries
-- =========================================================

create table if not exists animalstatuses (
    statusid int generated by default as identity primary key,
    statusname varchar(20) not null unique,
    constraint ck_animalstatuses_statusname_ru
        check (statusname in ('Доступен', 'Пристроен', 'На рассмотрении'))
);

create table if not exists roles (
    roleid int generated by default as identity primary key,
    rolename varchar(20) not null unique,
    constraint ck_roles_rolename
        check (rolename in ('Guest', 'Manager', 'Admin'))
);

create table if not exists animaltypes (
    typeid int generated by default as identity primary key,
    typename varchar(50) not null unique,
    constraint ck_animaltypes_typename_not_empty check (btrim(typename) <> '')
);

create table if not exists breeds (
    breedid int generated by default as identity primary key,
    breedname varchar(100) not null unique,
    typeid int not null references animaltypes(typeid) on delete cascade,
    constraint ck_breeds_breedname_not_empty check (btrim(breedname) <> '')
);

create table if not exists animalcharacters (
    characterid int generated by default as identity primary key,
    charactername varchar(50) not null unique,
    description varchar(255),
    constraint ck_animalcharacters_name_not_empty check (btrim(charactername) <> '')
);

create table if not exists shelters (
    shelterid int generated by default as identity primary key,
    sheltername varchar(100) not null unique,
    address varchar(255),
    phone varchar(20),
    email varchar(100),
    description text,
    isactive boolean not null default true,
    createddate timestamp not null default now(),
    constraint ck_shelters_name_not_empty check (btrim(sheltername) <> '')
);

-- =========================================================
-- Users and profiles
-- =========================================================

create table if not exists users (
    userid int generated by default as identity primary key,
    email varchar(100) not null unique,
    passwordhash varchar(255) not null,
    lastname varchar(50) not null,
    firstname varchar(50) not null,
    middlename varchar(50),
    phone varchar(20) not null,
    registrationdate timestamp not null default now(),
    roleid int not null references roles(roleid) on delete no action,
    shelterid int references shelters(shelterid),
    constraint ck_users_email_like check (position('@' in email) > 1),
    constraint ck_users_passwordhash_not_empty check (btrim(passwordhash) <> ''),
    constraint ck_users_lastname_not_empty check (btrim(lastname) <> ''),
    constraint ck_users_firstname_not_empty check (btrim(firstname) <> ''),
    constraint ck_users_phone_plus check (phone ~ '^\+[0-9].*')
);

create table if not exists userprofiles (
    profileid int generated by default as identity primary key,
    userid int not null unique references users(userid) on delete cascade,
    homeaddress varchar(255),
    dateofbirth date check (dateofbirth <= current_date),
    profilepicture varchar(255),
    createddate timestamp not null default now(),
    updateddate timestamp not null default now()
);

-- =========================================================
-- Animals
-- =========================================================

create table if not exists animals (
    animalid int generated by default as identity primary key,
    animalname varchar(50) not null,
    age int not null check (age >= 0),
    gender varchar(10) not null check (gender in ('Male', 'Female', 'Unknown')),
    vaccinated boolean not null default false,
    description text,
    imagepath varchar(255),
    statusid int not null references animalstatuses(statusid),
    breedid int not null references breeds(breedid) on delete cascade,
    characterid int references animalcharacters(characterid),
    height numeric(5,2) check (height > 0),
    animalweight numeric(5,2) check (animalweight > 0),
    admissiondate date,
    shelterid int references shelters(shelterid),
    constraint ck_animals_name_not_empty check (btrim(animalname) <> '')
);

create table if not exists animalmedia (
    mediaid int generated by default as identity primary key,
    animalid int not null references animals(animalid) on delete cascade,
    mediatype varchar(10) not null check (mediatype in ('Photo', 'Video')),
    mediapath varchar(500) not null,
    displayorder int not null default 0,
    isprimary boolean not null default false,
    createddate timestamp not null default now()
);

create index if not exists ix_animalmedia_animalid on animalmedia(animalid);
create index if not exists ix_animalmedia_displayorder on animalmedia(animalid, displayorder);

-- =========================================================
-- Applications
-- =========================================================

create table if not exists applicationstatuses (
    statusid int generated by default as identity primary key,
    statusname varchar(20) not null unique
        check (statusname in ('Pending', 'Approved', 'Rejected'))
);

create table if not exists applications (
    applicationid int generated by default as identity primary key,
    userid int not null references users(userid) on delete cascade,
    animalid int not null references animals(animalid) on delete cascade,
    applicationdate timestamp not null default now(),
    statusid int not null references applicationstatuses(statusid),
    reason varchar(500) not null check (btrim(reason) <> ''),
    experience varchar(500),
    housingconditions varchar(500),
    comment text
);

-- =========================================================
-- Messaging and donations
-- =========================================================

create table if not exists messages (
    messageid int generated by default as identity primary key,
    senderid int not null references users(userid),
    parentmessageid int references messages(messageid),
    subjectmessages varchar(200),
    messagetext text not null check (btrim(messagetext) <> ''),
    senddate timestamp not null default now(),
    isread boolean not null default false,
    recipientrole varchar(20) check (recipientrole in ('Manager', 'Admin') or recipientrole is null),
    recipientshelterid int references shelters(shelterid)
);

create table if not exists donations (
    donationid int generated by default as identity primary key,
    userid int not null references users(userid) on delete cascade,
    animalid int not null references animals(animalid) on delete cascade,
    amount numeric(10,2) not null check (amount > 0),
    donationdate timestamp not null default now(),
    comment varchar(255),
    isapproved boolean not null default false
);

create table if not exists news (
    newsid int generated by default as identity primary key,
    userid int not null references users(userid) on delete cascade,
    title varchar(100) not null check (btrim(title) <> ''),
    content text not null check (btrim(content) <> ''),
    postdate timestamp not null default now(),
    ispublished boolean not null default true,
    imagepath varchar(255),
    shelterid int references shelters(shelterid)
);

-- =========================================================
-- Meetings
-- =========================================================

create table if not exists meetingstatuses (
    meetingstatusid int generated by default as identity primary key,
    statusname varchar(20) not null unique
        check (statusname in ('Scheduled', 'InProgress', 'Completed', 'Cancelled', 'NoShow'))
);

create table if not exists videomeetings (
    meetingid int generated by default as identity primary key,
    applicationid int not null references applications(applicationid) on delete cascade,
    meetingstatusid int not null default 1 references meetingstatuses(meetingstatusid),
    meetingtitle varchar(200) not null check (btrim(meetingtitle) <> ''),
    meetingdescription varchar(500),
    meetinglink varchar(500) not null check (btrim(meetinglink) <> ''),
    scheduleddatetime timestamp not null,
    meetingduration int not null check (meetingduration > 0),
    createdbyuserid int not null references users(userid),
    createddatetime timestamp not null default now(),
    lastmodifieddatetime timestamp not null default now()
);

create table if not exists meetingparticipants (
    participantid int generated by default as identity primary key,
    meetingid int not null references videomeetings(meetingid) on delete cascade,
    userid int not null references users(userid),
    participantrole varchar(20) not null check (participantrole in ('Host', 'Attendee')),
    unique (meetingid, userid)
);

-- =========================================================
-- Medical and care
-- =========================================================

create table if not exists vaccinationtypes (
    vaccinationtypeid int generated by default as identity primary key,
    vaccinationname varchar(100) not null unique check (btrim(vaccinationname) <> ''),
    description varchar(255)
);

create table if not exists animalvaccinations (
    animalvaccinationid int generated by default as identity primary key,
    animalid int not null references animals(animalid) on delete cascade,
    vaccinationtypeid int not null references vaccinationtypes(vaccinationtypeid) on delete cascade
);

create table if not exists vaccinationrecords (
    recordid int generated by default as identity primary key,
    animalvaccinationid int not null references animalvaccinations(animalvaccinationid) on delete cascade,
    vaccinationdate date not null default current_date
);

create table if not exists animalmedicalrecords (
    recordid int generated by default as identity primary key,
    animalid int not null references animals(animalid) on delete cascade,
    conditionname varchar(100) not null,
    diagnosisdate date,
    treatment varchar(500),
    status varchar(20) default 'Active' check (status in ('Active', 'Resolved', 'Chronic')),
    notes text
);

create table if not exists activitytypes (
    activitytypeid int generated by default as identity primary key,
    activityname varchar(50) not null unique,
    description varchar(255)
);

create table if not exists frequencytypes (
    frequencyid int generated by default as identity primary key,
    frequencyname varchar(50) not null unique,
    description varchar(255)
);

create table if not exists animalcareschedule (
    scheduleid int generated by default as identity primary key,
    animalid int not null references animals(animalid) on delete cascade,
    activitytypeid int not null references activitytypes(activitytypeid),
    frequencyid int not null references frequencytypes(frequencyid),
    scheduletime time,
    notes varchar(255),
    isactive boolean default true
);

-- =========================================================
-- Audit + notifications
-- =========================================================

create table if not exists auditlogs (
    auditid int generated by default as identity primary key,
    tablename varchar(50) not null,
    recordid int not null,
    action varchar(20) not null,
    changedby int not null references users(userid),
    changedate timestamp not null default now(),
    oldvalue text,
    newvalue text
);

create table if not exists managernotifications (
    notificationid int generated by default as identity primary key,
    userid int not null references users(userid),
    message varchar(255) not null,
    createddate timestamp not null default now(),
    isread boolean not null default false
);

-- =========================================================
-- Functions + triggers
-- =========================================================

create or replace function trg_set_videomeeting_modified()
returns trigger
language plpgsql
as $$
begin
  new.lastmodifieddatetime := now();
  return new;
end;
$$;

drop trigger if exists trg_updatemeetingmodifieddate on videomeetings;
create trigger trg_updatemeetingmodifieddate
before update on videomeetings
for each row execute function trg_set_videomeeting_modified();

create or replace function trg_set_userprofile_updated()
returns trigger
language plpgsql
as $$
begin
  new.updateddate := now();
  return new;
end;
$$;

drop trigger if exists trg_updateuserprofiledate on userprofiles;
create trigger trg_updateuserprofiledate
before update on userprofiles
for each row execute function trg_set_userprofile_updated();

create or replace function trg_check_user_role_for_application()
returns trigger
language plpgsql
as $$
begin
  if exists (
      select 1
      from users u
      join roles r on r.roleid = u.roleid
      where u.userid = new.userid and r.rolename in ('Manager', 'Admin')
  ) then
    raise exception 'Managers and Admins cannot create adoption applications';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_checkuserroleforapplication on applications;
create trigger trg_checkuserroleforapplication
before insert on applications
for each row execute function trg_check_user_role_for_application();

create or replace function trg_notify_manager_on_application()
returns trigger
language plpgsql
as $$
declare
  v_manager_id int;
begin
  select u.userid
    into v_manager_id
  from users u
  join roles r on r.roleid = u.roleid
  where r.rolename = 'Manager'
  order by u.userid
  limit 1;

  if v_manager_id is not null then
    insert into managernotifications(userid, message)
    values (v_manager_id, 'Получена новая заявка на усыновление для AnimalID ' || new.animalid::text);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notifymanageronapplication on applications;
create trigger trg_notifymanageronapplication
after insert on applications
for each row execute function trg_notify_manager_on_application();

create or replace function trg_notify_manager_on_donation()
returns trigger
language plpgsql
as $$
declare
  v_manager_id int;
begin
  select u.userid
    into v_manager_id
  from users u
  join roles r on r.roleid = u.roleid
  where r.rolename = 'Manager'
  order by u.userid
  limit 1;

  if v_manager_id is not null then
    insert into managernotifications(userid, message)
    values (
      v_manager_id,
      'New donation received for AnimalID ' || new.animalid::text || ' with amount ' || new.amount::text
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notifymanagerondonation on donations;
create trigger trg_notifymanagerondonation
after insert on donations
for each row execute function trg_notify_manager_on_donation();

-- =========================================================
-- Views
-- =========================================================

create or replace view vw_meetingdetails as
select
    vm.meetingid,
    vm.meetingtitle,
    vm.meetingdescription,
    vm.meetinglink,
    vm.scheduleddatetime,
    vm.meetingduration,
    ms.statusname as meetingstatus,
    a.applicationid,
    (u_app.lastname || ' ' || u_app.firstname) as applicantname,
    anim.animalname,
    (u_creator.lastname || ' ' || u_creator.firstname) as createdbyname,
    vm.createddatetime
from videomeetings vm
join meetingstatuses ms on vm.meetingstatusid = ms.meetingstatusid
join applications a on vm.applicationid = a.applicationid
join users u_app on a.userid = u_app.userid
join animals anim on a.animalid = anim.animalid
join users u_creator on vm.createdbyuserid = u_creator.userid;

create or replace view vw_meetingparticipants as
select
    mp.participantid,
    mp.meetingid,
    vm.meetingtitle,
    u.userid,
    (u.lastname || ' ' || u.firstname) as participantname,
    u.email,
    mp.participantrole
from meetingparticipants mp
join videomeetings vm on mp.meetingid = vm.meetingid
join users u on mp.userid = u.userid;

create or replace view vw_animalcatalog as
select
    a.animalid,
    a.animalname,
    a.age,
    a.gender,
    a.vaccinated,
    a.height,
    a.animalweight,
    s.statusname as status,
    b.breedname,
    t.typename,
    ac.charactername,
    a.imagepath
from animals a
join breeds b on a.breedid = b.breedid
join animaltypes t on b.typeid = t.typeid
join animalstatuses s on a.statusid = s.statusid
left join animalcharacters ac on a.characterid = ac.characterid
where s.statusname = 'Доступен';

create or replace view vw_applicationreport as
select
    app.applicationid,
    ast.statusname as status,
    app.applicationdate,
    (u.firstname || ' ' || u.lastname) as username,
    r.rolename,
    a.animalname as animalname
from applications app
join applicationstatuses ast on app.statusid = ast.statusid
join users u on app.userid = u.userid
join roles r on u.roleid = r.roleid
join animals a on app.animalid = a.animalid;

create or replace view vw_animalvaccinations as
select
    a.animalid,
    a.animalname,
    vt.vaccinationname,
    vr.vaccinationdate
from animals a
join animalvaccinations av on a.animalid = av.animalid
join vaccinationtypes vt on av.vaccinationtypeid = vt.vaccinationtypeid
left join vaccinationrecords vr on av.animalvaccinationid = vr.animalvaccinationid;

create or replace view vw_breedstats as
select
    b.breedname,
    count(a.animalid) as animalcount
from animals a
join breeds b on a.breedid = b.breedid
group by b.breedname;

create or replace view vw_latestnews as
select
    n.newsid,
    n.title,
    n.content,
    n.postdate,
    (u.firstname || ' ' || u.lastname) as authorname,
    r.rolename
from news n
join users u on n.userid = u.userid
join roles r on u.roleid = r.roleid
where n.ispublished = true
order by n.postdate desc
limit 5;

-- =========================================================
-- Seed essentials
-- =========================================================

insert into roles (rolename)
values ('Guest'), ('Manager'), ('Admin')
on conflict (rolename) do nothing;

insert into animalstatuses (statusname)
values ('Доступен'), ('Пристроен'), ('На рассмотрении')
on conflict (statusname) do nothing;

insert into applicationstatuses (statusname)
values ('Pending'), ('Approved'), ('Rejected')
on conflict (statusname) do nothing;

