# Generated by Django 4.2.25 on 2026-05-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(db_column='newsid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('content', models.TextField(db_column='content')),
                ('post_date', models.DateTimeField(auto_now_add=True, db_column='postdate')),
                ('is_published', models.BooleanField(db_column='ispublished', default=True)),
                ('image_path', models.CharField(blank=True, db_column='imagepath', max_length=255, null=True)),
                ('shelter', models.ForeignKey(blank=True, db_column='shelterid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.shelter')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
