# Generated by Django 4.2.25 on 2026-05-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(db_column='animalid', primary_key=True, serialize=False)),
                ('animal_name', models.CharField(db_column='animalname', max_length=50)),
                ('age', models.IntegerField(db_column='age')),
                ('gender', models.CharField(db_column='gender', max_length=10)),
                ('vaccinated', models.BooleanField(db_column='vaccinated', default=False)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('image_path', models.CharField(blank=True, db_column='imagepath', max_length=255, null=True)),
                ('height', models.DecimalField(blank=True, db_column='height', decimal_places=2, max_digits=5, null=True)),
                ('animal_weight', models.DecimalField(blank=True, db_column='animalweight', decimal_places=2, max_digits=5, null=True)),
                ('admission_date', models.DateField(blank=True, db_column='admissiondate', null=True)),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'db_table': 'animals',
            },
        ),
        migrations.CreateModel(
            name='AnimalCharacter',
            fields=[
                ('character_id', models.AutoField(db_column='characterid', primary_key=True, serialize=False)),
                ('character_name', models.CharField(db_column='charactername', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Характер животного',
                'verbose_name_plural': 'Характеры животных',
                'db_table': 'animalcharacters',
            },
        ),
        migrations.CreateModel(
            name='AnimalStatus',
            fields=[
                ('status_id', models.AutoField(db_column='statusid', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='statusname', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Статус животного',
                'verbose_name_plural': 'Статусы животных',
                'db_table': 'animalstatuses',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('type_id', models.AutoField(db_column='typeid', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='typename', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Тип животного',
                'verbose_name_plural': 'Типы животных',
                'db_table': 'animaltypes',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('shelter_id', models.AutoField(db_column='shelterid', primary_key=True, serialize=False)),
                ('shelter_name', models.CharField(db_column='sheltername', max_length=100, unique=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('is_active', models.BooleanField(db_column='isactive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='createddate')),
            ],
            options={
                'verbose_name': 'Приют',
                'verbose_name_plural': 'Приюты',
                'db_table': 'shelters',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_id', models.AutoField(db_column='breedid', primary_key=True, serialize=False)),
                ('breed_name', models.CharField(db_column='breedname', max_length=100, unique=True)),
                ('type', models.ForeignKey(db_column='typeid', on_delete=django.db.models.deletion.CASCADE, to='animals.animaltype')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'db_table': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='AnimalMedia',
            fields=[
                ('media_id', models.AutoField(db_column='mediaid', primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('Photo', 'Фото'), ('Video', 'Видео')], db_column='mediatype', max_length=10)),
                ('media_path', models.CharField(db_column='mediapath', max_length=500)),
                ('display_order', models.IntegerField(db_column='displayorder', default=0)),
                ('is_primary', models.BooleanField(db_column='isprimary', default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='createddate')),
                ('animal', models.ForeignKey(db_column='animalid', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Медиа-файл животного',
                'verbose_name_plural': 'Медиа-файлы животных',
                'db_table': 'animalmedia',
                'ordering': ['display_order', 'media_id'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(db_column='breedid', on_delete=django.db.models.deletion.CASCADE, to='animals.breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='character',
            field=models.ForeignKey(blank=True, db_column='characterid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animalcharacter'),
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(blank=True, db_column='shelterid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.shelter'),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.ForeignKey(db_column='statusid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='animals.animalstatus'),
        ),
    ]
