"""
Django settings for shelter_project project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-p6jtvur592d(jy^_lol&a-cs=zl1=@%5h)v_lt5vtp5^p8g)2r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS - для локальной разработки пустой список, для Docker из переменной окружения
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = ALLOWED_HOSTS_ENV.split(',')
else:
    # Локальная разработка - разрешаем localhost и 127.0.0.1
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # External apps
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',

    # Local apps
    'accounts',
    'animals',
    'applications',
    'news',
    'donations',
    'meetings',
    'messages.apps.MessagesConfig',
    'care',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shelter_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context.auth_user',
                'messages.context.unread_messages',
                'animals.context.active_shelters',
            ],
        },
    },
]

WSGI_APPLICATION = 'shelter_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Настройки PostgreSQL из переменных окружения
# Важно: раньше проект использовал MSSQL и переменные DB_HOST/DB_NAME могли указывать на SQLEXPRESS.
# Чтобы не ловить ошибки, используем PG_* как приоритет, а DB_* только если это похоже на Postgres.
PG_HOST = os.environ.get('PG_HOST') or os.environ.get('PGHOST')
PG_NAME = os.environ.get('PG_NAME') or os.environ.get('PGDATABASE')
PG_USER = os.environ.get('PG_USER') or os.environ.get('PGUSER')
PG_PASSWORD = os.environ.get('PG_PASSWORD') or os.environ.get('PGPASSWORD')
PG_PORT = os.environ.get('PG_PORT') or os.environ.get('PGPORT')

_db_host_fallback = os.environ.get('DB_HOST', '127.0.0.1')
if '\\' in _db_host_fallback or 'SQLEXPRESS' in _db_host_fallback.upper():
    _db_host_fallback = '127.0.0.1'

DB_HOST = PG_HOST or _db_host_fallback
DB_NAME = PG_NAME or os.environ.get('DB_NAME', 'AnimalShelterDB')
DB_USER = PG_USER or os.environ.get('DB_USER', 'postgres')
# На локальной машине у проекта часто используется пароль postgres-пользователя "1"
DB_PASSWORD = PG_PASSWORD or os.environ.get('DB_PASSWORD', '1')
DB_PORT = PG_PORT or os.environ.get('DB_PORT', '5432')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'OPTIONS': {
            # Windows иногда возвращает сообщения libpq не в UTF-8 → psycopg2 падает с UnicodeDecodeError.
            # Принудительно выставляем кодировку клиента.
            'options': '-c client_encoding=UTF8',
        },
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# DRF & Spectacular
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Анималити API',
    'DESCRIPTION': 'API для приюта животных',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings (Mail.ru SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = int(os.environ.get('MAILRU_EMAIL_PORT', '465'))
EMAIL_HOST_USER = os.environ.get('MAILRU_EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('MAILRU_EMAIL_PASSWORD', '')
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'no-reply@example.com'
