# Generated by Django 4.2.25 on 2026-05-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='roleid', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='rolename', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=100, unique=True)),
                ('password_hash', models.CharField(db_column='passwordhash', max_length=255)),
                ('last_name', models.CharField(db_column='lastname', max_length=50)),
                ('first_name', models.CharField(db_column='firstname', max_length=50)),
                ('middle_name', models.CharField(blank=True, db_column='middlename', max_length=50, null=True)),
                ('phone', models.CharField(db_column='phone', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='registrationdate')),
                ('role', models.ForeignKey(db_column='roleid', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.role')),
                ('shelter', models.ForeignKey(blank=True, db_column='shelterid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.shelter')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(db_column='profileid', primary_key=True, serialize=False)),
                ('home_address', models.CharField(blank=True, db_column='homeaddress', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='dateofbirth', null=True)),
                ('profile_picture', models.CharField(blank=True, db_column='profilepicture', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='createddate')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updateddate')),
                ('user', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'userprofiles',
            },
        ),
    ]
