# Generated by Django 4.2.25 on 2026-05-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(db_column='donationid', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=10)),
                ('donation_date', models.DateTimeField(auto_now_add=True, db_column='donationdate')),
                ('comment', models.TextField(blank=True, db_column='comment', null=True)),
                ('is_approved', models.BooleanField(db_column='isapproved', default=True)),
                ('animal', models.ForeignKey(db_column='animalid', on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
                'db_table': 'donations',
            },
        ),
    ]
